khs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.khs, name='khs'),
    path('<int:mahasiswa_id>/', views.khs_detail, name='khs_detail'),
]

sistem_informasi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('mahasiswa/', include('mahasiswa.urls')),
    path('angkatan/', include('angkatan.urls')),
    path('pengajar/', include('dosen_pengajar.urls')),
    path('absen/', include('absen.urls')),
    path('matakuliah/', include('matakuliah.urls')),
    path('dosenwali/', include('dosenwali.urls')),
    path('tahun_ajaran/', include('tahun_ajaran.urls')),
    path('user_manage/', include('user_manage.urls')),
    path('authentication/', include('authentication.urls')),
    path('cuti/', include('cuti.urls')),
    path('nilai/', include('nilai.urls')),
    path('krs/', include('krs.urls')),
    path('khs/', include('khs.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

khs/models.py
from django.db import models

# Create your models here.

krs/models.py
from django.db import models
from mahasiswa.models import Mahasiswa


class KRS(models.Model):
    mahasiswa = models.ForeignKey(Mahasiswa, on_delete=models.CASCADE)
    mata_kuliah = models.CharField(max_length=200)
    status = models.CharField(max_length=20, default='belum disetujui')
    nilai = models.CharField(max_length=20, null=True, blank=True)  # Contoh DecimalField untuk nilai

    def __str__(self):
        return f"{self.mahasiswa} - {self.mata_kuliah}"

class MataKuliah(models.Model):
    kode = models.CharField(max_length=10)
    nama = models.CharField(max_length=100)
    jumlah_sks = models.IntegerField(default=0)

    def __str__(self):
        return self.nama
    

khs/views.py
from django.shortcuts import render
from krs.models import KRS
from mahasiswa.models import Mahasiswa
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from matakuliah.models import MataKuliah


@login_required
def khs(request):

    user = request.user

    try:
        mahasiswa_khs = Mahasiswa.objects.filter(nim=user.NIM)
    except Mahasiswa.DoesNotExist:
        mahasiswa_khs = None

    if mahasiswa_khs:
        mhs_khs = KRS.objects.filter(mahasiswa_id=user.NIM)

        nama_khs = []

        for krs in mhs_khs:
            nama_khs.extend(krs.mata_kuliah.split(', '))

        khs_unik = KRS.objects.filter(mahasiswa_id=user.NIM)

    else:
        khs_unik = []

    jurusan = request.GET.get('jurusan', None)

    if jurusan:
        if jurusan == 'semua_jurusan':
            krs_dinilai = KRS.objects.filter(nilai__isnull=False)
        else:
            krs_dinilai = KRS.objects.filter(
                mahasiswa__jurusan=jurusan, nilai__isnull=False)
    else:
        krs_dinilai = KRS.objects.filter(nilai__isnull=False)

    context = {
        'title': 'KHS',
        'krs_dinilai': krs_dinilai,
        'khs_unik': khs_unik,
    }

    return render(request, 'khs.html', context)


@login_required
def khs_detail(request, mahasiswa_id):
    # Mengambil objek KRS yang memiliki mahasiswa_id sesuai dengan parameter yang diberikan.
    krs_dinilai = get_object_or_404(
        KRS, mahasiswa_id=mahasiswa_id, nilai__isnull=False)

    # Memisahkan mata kuliah dan nilai menjadi daftar.
    matakuliah_list = krs_dinilai.mata_kuliah.split(',')
    nilai_list = krs_dinilai.nilai.split(',')
    data = zip(matakuliah_list, nilai_list)

    context = {
        'title': 'KHS',
        'mahasiswa': krs_dinilai.mahasiswa,
        'data': data,
    }

    return render(request, 'khs_detail.html', context)

khs/templates/khs.html
{% extends "base.html" %}

{% block content %}
<h1>Daftar Mahasiswa dengan KRS yang Sudah Dinilai</h1>
{% if user.is_authenticated and user.role == "Akademik" %}
    <form action="{% url 'khs' %}" method="GET">
        <div class="box-container">
            <div class="box">
                <input form-check-input type="radio" name="jurusan" value="" id="semua_jurusan"
                {% if not request.GET.jurusan %} checked{% endif %}>
                <label form-check-label for="semua_jurusan">Semua Jurusan</label>
            </div>
        
        
            <div class="box">
                <input form-check-input type="radio" name="jurusan" value="Teknologi Informasi" id="Teknologi Informasi" 
                {% if request.GET.jurusan == 'Teknologi Informasi' %} checked{% endif %}>
                <label form-check-label for="Teknologi Informasi">Teknologi Informasi</label>
            </div>
        
            <div class="box">
                <input form-check-input type="radio" name="jurusan" value="Akuntansi" id="Akuntansi" 
                {% if request.GET.jurusan == 'Akuntansi' %} checked{% endif %}>
                <label form-check-label for="Akuntansi">Akuntansi</label>
            </div>
        
            <div class="box">
                <input form-check-input type="radio" name="jurusan" value="Mekatronika" id="Mekatronika"
                {% if request.GET.jurusan == 'Mekatronika' %} checked{% endif %}>
                <label form-check-label for="Mekatronika">Mekatronika</label>
            </div>
        
            <div class="box">
                <input form-check-input type="radio" name="jurusan" value="Teknik Elektro" id="Teknik Elektro"
                {% if request.GET.jurusan == 'Teknik Elektro' %} checked{% endif %}>
                <label form-check-label for="Teknik Elektro">Teknik Elektro</label>
            </div>
        </div>
        
        <button type="submit" class="btn btn-primary d-flex align-items-center justify-content-between mt-2 mb-2">Submit <ion-icon name="arrow-forward-outline"></ion-icon> </button>
    </form>
{% endif %}
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>No</th>
            <th>NIM</th>
            <th>Nama Mahasiswa</th>
            <th>JK</th>
            <th>Angkatan</th>
            <th>Jumlah KRS</th>
            <th>Aksi</th>
        </tr>
    </thead>
    <tbody>
        {% for krs in khs_unik %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ krs.mahasiswa.nim }}</td>
                    <td>{{ krs.mahasiswa.nama }}</td>
                    <td>{{ krs.mahasiswa.jk }}</td>
                    <td>{{ krs.mahasiswa.angkatan }}</td>
                    <td>{{ krs.mahasiswa.krs_set.count }}</td>
                    <td><a href="{% url 'khs_detail' krs.mahasiswa.nim %}">Lihat KHS</a></td>
                </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

khs/templates/khs_detail.html
{% extends "base.html" %}

{% block content %}
<h3>Nama : {{ mahasiswa.nama }}</h3>
<h3>Nim : {{ mahasiswa.nim }}</h3>
<h3>Prodi : {{ mahasiswa.jurusan }}</h3>
<h3>Angkatan : {{ mahasiswa.angkatan }}</h3>
<h3>Semester : {{ mahasiswa.semester }}</h3>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>No</th>
            <th>Mata Kuliah</th>
            <th>Nilai</th>
        </tr>
    </thead>
    <tbody>
        {% for mata_kuliah, nilai in data %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ mata_kuliah }}</td>
                <td>{{ nilai }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}